//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 05:11:33 PM CEST 
//


package UF04.P02Dao_Dao;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for dataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clientes" type="{}clientesType"/>
 *         &lt;element name="empleados" type="{}empleadosType"/>
 *         &lt;element name="facturas" type="{}facturasType"/>
 *         &lt;element name="productos" type="{}productosType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataType", propOrder = {
    "clientes",
    "empleados",
    "facturas",
    "productos"
})
@XmlRootElement(name = "data")
public class DataType {

    @XmlElement(required = true)
    protected ClientesType clientes;
    @XmlElement(required = true)
    protected EmpleadosType empleados;
    @XmlElement(required = true)
    protected FacturasType facturas;
    @XmlElement(required = true)
    protected ProductosType productos;

    /**
     * Gets the value of the clientes property.
     * 
     * @return
     *     possible object is
     *     {@link ClientesType }
     *     
     */
    public ClientesType getClientes() {
        return clientes;
    }

    /**
     * Sets the value of the clientes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientesType }
     *     
     */
    public void setClientes(ClientesType value) {
        this.clientes = value;
    }

    /**
     * Gets the value of the empleados property.
     * 
     * @return
     *     possible object is
     *     {@link EmpleadosType }
     *     
     */
    public EmpleadosType getEmpleados() {
        return empleados;
    }

    /**
     * Sets the value of the empleados property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmpleadosType }
     *     
     */
    public void setEmpleados(EmpleadosType value) {
        this.empleados = value;
    }

    /**
     * Gets the value of the facturas property.
     * 
     * @return
     *     possible object is
     *     {@link FacturasType }
     *     
     */
    public FacturasType getFacturas() {
        return facturas;
    }

    /**
     * Sets the value of the facturas property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacturasType }
     *     
     */
    public void setFacturas(FacturasType value) {
        this.facturas = value;
    }

    /**
     * Gets the value of the productos property.
     * 
     * @return
     *     possible object is
     *     {@link ProductosType }
     *     
     */
    public ProductosType getProductos() {
        return productos;
    }

    /**
     * Sets the value of the productos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductosType }
     *     
     */
    public void setProductos(ProductosType value) {
        this.productos = value;
    }

}
