//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 05:11:33 PM CEST 
//


package UF04.P02Dao_Dao;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for facturaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="facturaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dni_cliente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id_producto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="precio_unidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="precio_total" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="iva" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "facturaType", propOrder = {
    "dniCliente",
    "idProducto",
    "precioUnidad",
    "precioTotal",
    "iva"
})
@XmlRootElement(name = "factura")
public class FacturaType {

    @XmlElement(name = "dni_cliente", required = true)
    protected String dniCliente;
    @XmlElement(name = "id_producto", required = true)
    protected String idProducto;
    @XmlElement(name = "precio_unidad", required = true)
    protected String precioUnidad;
    @XmlElement(name = "precio_total", required = true)
    protected String precioTotal;
    @XmlElement(required = true)
    protected String iva;

    /**
     * Gets the value of the dniCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDniCliente() {
        return dniCliente;
    }

    /**
     * Sets the value of the dniCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDniCliente(String value) {
        this.dniCliente = value;
    }

    /**
     * Gets the value of the idProducto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdProducto() {
        return idProducto;
    }

    /**
     * Sets the value of the idProducto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdProducto(String value) {
        this.idProducto = value;
    }

    /**
     * Gets the value of the precioUnidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecioUnidad() {
        return precioUnidad;
    }

    /**
     * Sets the value of the precioUnidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecioUnidad(String value) {
        this.precioUnidad = value;
    }

    /**
     * Gets the value of the precioTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecioTotal() {
        return precioTotal;
    }

    /**
     * Sets the value of the precioTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecioTotal(String value) {
        this.precioTotal = value;
    }

    /**
     * Gets the value of the iva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIva() {
        return iva;
    }

    /**
     * Sets the value of the iva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIva(String value) {
        this.iva = value;
    }

}
