//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 05:11:33 PM CEST 
//


package UF04.P02Dao_Dao;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Data_QNAME = new QName("", "data");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link FacturaType }
     * 
     */
    public FacturaType createFacturaType() {
        return new FacturaType();
    }

    /**
     * Create an instance of {@link ProductosType }
     * 
     */
    public ProductosType createProductosType() {
        return new ProductosType();
    }

    /**
     * Create an instance of {@link ClientesType }
     * 
     */
    public ClientesType createClientesType() {
        return new ClientesType();
    }

    /**
     * Create an instance of {@link EmpleadosType }
     * 
     */
    public EmpleadosType createEmpleadosType() {
        return new EmpleadosType();
    }

    /**
     * Create an instance of {@link ProductoType }
     * 
     */
    public ProductoType createProductoType() {
        return new ProductoType();
    }

    /**
     * Create an instance of {@link EmpleadoType }
     * 
     */
    public EmpleadoType createEmpleadoType() {
        return new EmpleadoType();
    }

    /**
     * Create an instance of {@link FacturasType }
     * 
     */
    public FacturasType createFacturasType() {
        return new FacturasType();
    }

    /**
     * Create an instance of {@link ClienteType }
     * 
     */
    public ClienteType createClienteType() {
        return new ClienteType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "data")
    public JAXBElement<DataType> createData(DataType value) {
        return new JAXBElement<DataType>(_Data_QNAME, DataType.class, null, value);
    }

}
